\documentclass[]{elsarticle} %review=doublespace preprint=single 5p=2 column
%%% Begin My package additions %%%%%%%%%%%%%%%%%%%
\usepackage[hyphens]{url}

  \journal{Transport Findings} % Sets Journal name


\usepackage{lineno} % add
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}

\usepackage{graphicx}
\usepackage{booktabs} % book-quality tables
%%%%%%%%%%%%%%%% end my additions to header

\usepackage[T1]{fontenc}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \usepackage{fontspec}
  \ifxetex
    \usepackage{xltxtra,xunicode}
  \fi
  \defaultfontfeatures{Mapping=tex-text,Scale=MatchLowercase}
  \newcommand{\euro}{€}
\fi
% use microtype if available
\IfFileExists{microtype.sty}{\usepackage{microtype}}{}
\bibliographystyle{elsarticle-harv}
\usepackage{graphicx}
\ifxetex
  \usepackage[setpagesize=false, % page size defined by xetex
              unicode=false, % unicode breaks when used with xetex
              xetex]{hyperref}
\else
  \usepackage[unicode=true]{hyperref}
\fi
\hypersetup{breaklinks=true,
            bookmarks=true,
            pdfauthor={},
            pdftitle={Changes in trip-making frequency by mode during the COVID-19 emergency: evidence from an online survey in Bangladesh},
            colorlinks=false,
            urlcolor=blue,
            linkcolor=magenta,
            pdfborder={0 0 0}}
\urlstyle{same}  % don't use monospace font for urls

\setcounter{secnumdepth}{0}
% Pandoc toggle for numbering sections (defaults to be off)
\setcounter{secnumdepth}{0}


% Pandoc header
\usepackage{float} \usepackage{xcolor} \floatplacement{figure}{H}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}



\begin{document}
\begin{frontmatter}

  \title{Changes in trip-making frequency by mode during the COVID-19 emergency:
evidence from an online survey in Bangladesh}
    \author[McMaster University]{Shaila Jamal}
   \ead{jamals16@mcmaster.ca} 
    \author[McMaster University]{Antonio Paez\corref{1}}
   \ead{paezha@mcmaster.ca} 
      \address[McMaster University]{School of Earth, Environment and Society, McMaster University, Hamilton,
ON, L8S 4K1, Canada}
      \cortext[1]{Corresponding Author}
  
  \begin{abstract}
  The COVID-19 pandemic has had a profound impact on mobility in every
  country and region around the world. Recent studies help to illuminate
  some of the dimensions of change - however, the evidence is still scant
  in developing countries. The objective of this paper is to present an
  exploratory analysis of the changes in the frequency of trip-making by
  mode during the COVID-19 emergency in Bangladesh. The analysis is based
  on an online sample conducted during the pandemic, and the results
  confirm an overall loss of mobility, especially among younger people, in
  the form of reduced trip-making frequency by all modes. In addition, the
  results suggest that changes are not uniform across modes, and in
  particular the loss of mobility was more pronounced for bus, rickshaw,
  and CNG auto-rickshaw. In contrast, there was some adoption of walking
  during the pandemic.
  \end{abstract}
  
 \end{frontmatter}

\hypertarget{research-questions-and-hypotheses}{%
\section{Research Questions and
Hypotheses}\label{research-questions-and-hypotheses}}

The spread of the COVID-19 pandemic has led to limitations to movement
in many countries and regions, either because of lock-down policies or
self-censoring by segments of the public. The magnitude of changes in
mobility has been studied by recent research, including DeWeese et al.
(2020) and Molloy et al. (2020). While the evidence available indicates
that although the overall mobility has reduced in much of the world, the
changes were uneven depending on the mode of transportation or the
purpose of the trip (see Lock, 2020; Paez, 2020). Unfortunately, with
few exceptions, evidence remains more spotty for developing countries,
most of which have large population segments that are less able to
absorb losses in mobility (e.g., Astroza et al., 2020; Huynh, 2020; Saha
et al., 2020).

The objective of this paper is to investigate changes in the trip-making
frequency by different modes of transportation during the COVID-19
emergency in Bangladesh. Using data from a recent online survey that
asked respondents to report mobility levels before and during the
pandemic, we pose the following questions:

\begin{itemize}
\tightlist
\item
  Was there a reduction of mobility in Bangladesh during COVID-19?
\item
  And if so, what forms of transportation were more affected?
\end{itemize}

This paper is a reproducible research document (see Brunsdon and Comber,
2020); the code and data necessary to reproduce the tables and figures
are available in a public
repository\footnote{\url{https://github.com/paezha/Frequency-of-Travel-by-Mode-COVID-19-Bangladesh}}

\hypertarget{methods-and-data}{%
\section{Methods and Data}\label{methods-and-data}}

Data used for this paper come from an online survey, ``Exploring the
potential of travel mode change behavior in the post-lock-down and
post-pandemic (COVID-19) period'', conducted during July - August 2020
in Bangladesh (\(n=800\)). The survey was disseminated through various
electronic means along with a widespread social media campaign and
promotion in various social media sites and groups. In addition to the
respondents' socio-demographic information, the survey covered different
aspects of travel such as travel behavior before and during COVID-19,
knowledge related to COVID-19, and opinions and perceptions regarding
travel behavior after lock-down and post-pandemic situation.

Like other surveys conducted during COVID-19 (e.g., Astroza et al.,
2020), this is a convenience sample. Convenience samples have the
advantage of being quick and cost-efficient and, despite their lower
generalizability, when they are homogeneous they are useful to address
rapidly emerging questions (Fricker and Schonlau, 2002; Jager et al.,
2017). This particular data set has an over-representation of the 16-30
years age group, whereas 37\% of the country's population belongs to
this group (Bangladesh Bureau of Statistics, 2015). Also, 66\% of the
respondents are male and 32\% are females compared to country's 49:51
male-female ratio (Bangladesh Bureau of Statistics, 2015). These
characteristics of the sample are expected in terms of online surveys as
young adults are more familiar with online platforms, especially in the
context of a developing country context. Also, in the case of
Bangladesh, collecting a representative sample remains difficult because
of overall public reluctance to participate, with women's strong
unwillingness to share their information to unknown parties in
particular in face-to-face interviews (see Jamal et al., 2020). In fact,
compared to Jamal et al.~{[}(2020); Table 1{]}, who had only 15\% of
responses from females, the online survey used in the present research
achieved greater penetration among women.

In terms of geography, respondents were asked to identify the name of
the district they reside. The resulting sample has 48\% of respondents
who live in Dhaka. Although, there are some differences in availability
of transportation services between cities, especially between Dhaka and
cities outside Dhaka, the mode use frequency indicates that only 15\%
never used buses and 32\% never used ride-hailing services before
COVID-19, which means these modes were available to most of the
respondents and a vast majority has used them to some extent before the
lock-down.

Given the above characteristics, the sample cannot be said to be a
probabilistic random sample, but is rather homogeneous for urban,
younger respondents, and has greater representation from females than
comparable samples obtained from face-to-face interviews in Bangladesh.

The context for the study was the country-wide emergency situation
during COVID-19, with required physical distancing recommendations and
relevant health regulations in place. Bangladesh was under partial
lock-down during the survey period, with only essential services open,
offices running on a rotation basis, all educational institutes closed,
and public transport services running at 50\% capacity. For the purpose
of this paper, we use two questions that provide information about
trip-making frequency by eight modes of transportation. The modes are
\textbf{car}, \textbf{ride-hailing} (e.g., Uber, Pathao),
\textbf{rickshaw}, \textbf{CNG auto-rickshaw} (a rickshaw-like vehicle
powered by compressed natural gas), \textbf{bus}, motorcycle/scooter
(hereafter just \textbf{motorcycle}), \textbf{walking}, and
\textbf{bicycle} (there was an additional catch-all category
\textbf{other} which we ignore here). Participants in the survey used
the following levels to report their frequency of traveling by each mode
both before and during COVID-19: \emph{Never}, \emph{Rarely}, \emph{Once
a week}, \emph{2-3 trips per week}, \emph{4-5 trips per week},
\emph{Almost daily}.

To describe changes in travel frequency by mode in the transition to the
pandemic, we use well-established exploratory data analysis (EDA)
techniques.

\hypertarget{findings}{%
\section{Findings}\label{findings}}

Figure \ref{fig:column-plot-cases} shows the number of responses (out of
800) in each trip-making frequency class by mode of transportation. The
white bars and gray bars are for travel before and during the pandemic,
respectively. Considering travel before the pandemic, travel by
rickshaw, and bus were relatively common for many respondents (few
respondents reported \emph{never} using these modes). The mode most
commonly used on a quotidian basis was walk. In contrast, respondents
reported less frequent travel by car, ride-hailing services, CNG
auto-rickshaw, motorcycle, and bicycle. During the pandemic, we see that
while there were reductions in mobility by car, motorcycle, and bicycle
(with more respondents reporting never traveling by these modes), the
changes were relatively minor.

\begin{figure}
\centering
\includegraphics{Frequency-of-Travel-by-Mode-COVID-19-Bangladesh_files/figure-latex/column-plot-cases-before-after-1.pdf}
\caption{\label{fig:column-plot-cases}Number of responses by trip-making
frequency class and mode, before and during COVID-19}
\end{figure}

\begin{table}[H]

\caption{\label{tab:table-transitions}\label{tab:cross-tabulation} Cross-tabulation of counts of travel frequency by mode, before and during COVID-19}
\centering
\resizebox{\linewidth}{!}{
\begin{tabular}[t]{lllllll}
\toprule
\multicolumn{1}{c}{ } & \multicolumn{6}{c}{During} \\
\cmidrule(l{3pt}r{3pt}){2-7}
Before & Never & Rarely & Once a week & 2-3 times per week & 4-5 times per week & Almost daily\\
\midrule
\addlinespace[0.3em]
\multicolumn{7}{l}{\textbf{car}}\\
\hspace{1em}Never & \cellcolor[HTML]{0D0887}{\textcolor{white}{\textbf{267}}} & \cellcolor[HTML]{F79242}{\textcolor{white}{\textbf{20}}} & \cellcolor[HTML]{FBA238}{\textcolor{white}{\textbf{5}}} & \cellcolor[HTML]{FCA636}{\textcolor{white}{\textbf{1}}} & \cellcolor[HTML]{FCA636}{\textcolor{white}{\textbf{1}}} & \cellcolor[HTML]{FCA537}{\textcolor{white}{\textbf{2}}}\\
\hspace{1em}Rarely & \cellcolor[HTML]{0D0887}{\textcolor{white}{\textbf{142}}} & \cellcolor[HTML]{7D03A8}{\textcolor{white}{\textbf{99}}} & \cellcolor[HTML]{F1824C}{\textcolor{white}{\textbf{21}}} & \cellcolor[HTML]{F79442}{\textcolor{white}{\textbf{12}}} & \cellcolor[HTML]{F99A3E}{\textcolor{white}{\textbf{9}}} & \cellcolor[HTML]{FCA636}{\textcolor{white}{\textbf{3}}}\\
\hspace{1em}Once a week & \cellcolor[HTML]{C13B82}{\textcolor{white}{\textbf{11}}} & \cellcolor[HTML]{0D0887}{\textcolor{white}{\textbf{23}}} & \cellcolor[HTML]{5801A4}{\textcolor{white}{\textbf{19}}} & \cellcolor[HTML]{E26660}{\textcolor{white}{\textbf{7}}} & \cellcolor[HTML]{FCA636}{\textcolor{white}{\textbf{2}}} & \cellcolor[HTML]{F9993E}{\textcolor{white}{\textbf{3}}}\\
\hspace{1em}2-3 times per week & \cellcolor[HTML]{CA457A}{\textcolor{white}{\textbf{10}}} & \cellcolor[HTML]{0D0887}{\textcolor{white}{\textbf{23}}} & \cellcolor[HTML]{E26660}{\textcolor{white}{\textbf{7}}} & \cellcolor[HTML]{E97257}{\textcolor{white}{\textbf{6}}} & \cellcolor[HTML]{DB5C68}{\textcolor{white}{\textbf{8}}} & \cellcolor[HTML]{FCA636}{\textcolor{white}{\textbf{2}}}\\
\hspace{1em}4-5 times per week & \cellcolor[HTML]{FCA636}{\textcolor{white}{\textbf{4}}} & \cellcolor[HTML]{910EA3}{\textcolor{white}{\textbf{9}}} & \cellcolor[HTML]{F1844C}{\textcolor{white}{\textbf{5}}} & \cellcolor[HTML]{E16462}{\textcolor{white}{\textbf{6}}} & \cellcolor[HTML]{0D0887}{\textcolor{white}{\textbf{12}}} & \cellcolor[HTML]{FCA636}{\textcolor{white}{\textbf{4}}}\\
\hspace{1em}Almost daily & \cellcolor[HTML]{D8576B}{\textcolor{white}{\textbf{6}}} & \cellcolor[HTML]{6A00A8}{\textcolor{white}{\textbf{15}}} & \cellcolor[HTML]{D8576B}{\textcolor{white}{\textbf{6}}} & \cellcolor[HTML]{B12A90}{\textcolor{white}{\textbf{10}}} & \cellcolor[HTML]{FCA636}{\textcolor{white}{\textbf{0}}} & \cellcolor[HTML]{0D0887}{\textcolor{white}{\textbf{20}}}\\
\addlinespace[0.3em]
\multicolumn{7}{l}{\textbf{ride-hailing}}\\
\hspace{1em}Never & \cellcolor[HTML]{0D0887}{\textcolor{white}{\textbf{254}}} & \cellcolor[HTML]{F9983E}{\textcolor{white}{\textbf{13}}} & \cellcolor[HTML]{FB9F3A}{\textcolor{white}{\textbf{6}}} & \cellcolor[HTML]{FBA238}{\textcolor{white}{\textbf{4}}} & \cellcolor[HTML]{FCA636}{\textcolor{white}{\textbf{0}}} & \cellcolor[HTML]{FCA636}{\textcolor{white}{\textbf{0}}}\\
\hspace{1em}Rarely & \cellcolor[HTML]{0D0887}{\textcolor{white}{\textbf{192}}} & \cellcolor[HTML]{E56A5D}{\textcolor{white}{\textbf{44}}} & \cellcolor[HTML]{F89540}{\textcolor{white}{\textbf{12}}} & \cellcolor[HTML]{FCA636}{\textcolor{white}{\textbf{1}}} & \cellcolor[HTML]{FCA636}{\textcolor{white}{\textbf{1}}} & \cellcolor[HTML]{FCA636}{\textcolor{white}{\textbf{1}}}\\
\hspace{1em}Once a week & \cellcolor[HTML]{0D0887}{\textcolor{white}{\textbf{60}}} & \cellcolor[HTML]{D35171}{\textcolor{white}{\textbf{20}}} & \cellcolor[HTML]{AC2794}{\textcolor{white}{\textbf{31}}} & \cellcolor[HTML]{F9983E}{\textcolor{white}{\textbf{3}}} & \cellcolor[HTML]{FBA238}{\textcolor{white}{\textbf{1}}} & \cellcolor[HTML]{FCA636}{\textcolor{white}{\textbf{0}}}\\
\hspace{1em}2-3 times per week & \cellcolor[HTML]{0D0887}{\textcolor{white}{\textbf{49}}} & \cellcolor[HTML]{E26561}{\textcolor{white}{\textbf{12}}} & \cellcolor[HTML]{EB7557}{\textcolor{white}{\textbf{9}}} & \cellcolor[HTML]{F07F4F}{\textcolor{white}{\textbf{7}}} & \cellcolor[HTML]{FA9B3D}{\textcolor{white}{\textbf{2}}} & \cellcolor[HTML]{FCA636}{\textcolor{white}{\textbf{0}}}\\
\hspace{1em}4-5 times per week & \cellcolor[HTML]{0D0887}{\textcolor{white}{\textbf{28}}} & \cellcolor[HTML]{D8576B}{\textcolor{white}{\textbf{10}}} & \cellcolor[HTML]{FA9B3D}{\textcolor{white}{\textbf{3}}} & \cellcolor[HTML]{F3874A}{\textcolor{white}{\textbf{5}}} & \cellcolor[HTML]{EF7C51}{\textcolor{white}{\textbf{6}}} & \cellcolor[HTML]{FCA636}{\textcolor{white}{\textbf{2}}}\\
\hspace{1em}Almost daily & \cellcolor[HTML]{0D0887}{\textcolor{white}{\textbf{14}}} & \cellcolor[HTML]{E66C5C}{\textcolor{white}{\textbf{3}}} & \cellcolor[HTML]{DB5C68}{\textcolor{white}{\textbf{4}}} & \cellcolor[HTML]{F79242}{\textcolor{white}{\textbf{1}}} & \cellcolor[HTML]{FCA636}{\textcolor{white}{\textbf{0}}} & \cellcolor[HTML]{F07F4F}{\textcolor{white}{\textbf{2}}}\\
\addlinespace[0.3em]
\multicolumn{7}{l}{\textbf{rickshaw}}\\
\hspace{1em}Never & \cellcolor[HTML]{0D0887}{\textcolor{white}{\textbf{51}}} & \cellcolor[HTML]{EB7655}{\textcolor{white}{\textbf{9}}} & \cellcolor[HTML]{F3854B}{\textcolor{white}{\textbf{6}}} & \cellcolor[HTML]{FCA636}{\textcolor{white}{\textbf{0}}} & \cellcolor[HTML]{FBA139}{\textcolor{white}{\textbf{1}}} & \cellcolor[HTML]{FCA636}{\textcolor{white}{\textbf{0}}}\\
\hspace{1em}Rarely & \cellcolor[HTML]{340498}{\textcolor{white}{\textbf{64}}} & \cellcolor[HTML]{0D0887}{\textcolor{white}{\textbf{70}}} & \cellcolor[HTML]{E26561}{\textcolor{white}{\textbf{18}}} & \cellcolor[HTML]{F99A3E}{\textcolor{white}{\textbf{4}}} & \cellcolor[HTML]{FA9E3B}{\textcolor{white}{\textbf{3}}} & \cellcolor[HTML]{FCA636}{\textcolor{white}{\textbf{1}}}\\
\hspace{1em}Once a week & \cellcolor[HTML]{6001A6}{\textcolor{white}{\textbf{36}}} & \cellcolor[HTML]{4F02A2}{\textcolor{white}{\textbf{38}}} & \cellcolor[HTML]{0D0887}{\textcolor{white}{\textbf{45}}} & \cellcolor[HTML]{F07F4F}{\textcolor{white}{\textbf{9}}} & \cellcolor[HTML]{FCA636}{\textcolor{white}{\textbf{3}}} & \cellcolor[HTML]{FCA636}{\textcolor{white}{\textbf{3}}}\\
\hspace{1em}2-3 times per week & \cellcolor[HTML]{2C0594}{\textcolor{white}{\textbf{34}}} & \cellcolor[HTML]{0D0887}{\textcolor{white}{\textbf{36}}} & \cellcolor[HTML]{BE3885}{\textcolor{white}{\textbf{18}}} & \cellcolor[HTML]{6100A7}{\textcolor{white}{\textbf{29}}} & \cellcolor[HTML]{F89441}{\textcolor{white}{\textbf{6}}} & \cellcolor[HTML]{FCA636}{\textcolor{white}{\textbf{4}}}\\
\hspace{1em}4-5 times per week & \cellcolor[HTML]{9511A1}{\textcolor{white}{\textbf{21}}} & \cellcolor[HTML]{0D0887}{\textcolor{white}{\textbf{30}}} & \cellcolor[HTML]{FCA636}{\textcolor{white}{\textbf{7}}} & \cellcolor[HTML]{C8437B}{\textcolor{white}{\textbf{16}}} & \cellcolor[HTML]{D04D73}{\textcolor{white}{\textbf{15}}} & \cellcolor[HTML]{F99A3E}{\textcolor{white}{\textbf{8}}}\\
\hspace{1em}Almost daily & \cellcolor[HTML]{99159F}{\textcolor{white}{\textbf{45}}} & \cellcolor[HTML]{0D0887}{\textcolor{white}{\textbf{65}}} & \cellcolor[HTML]{DB5C68}{\textcolor{white}{\textbf{30}}} & \cellcolor[HTML]{FA9B3D}{\textcolor{white}{\textbf{18}}} & \cellcolor[HTML]{FCA636}{\textcolor{white}{\textbf{16}}} & \cellcolor[HTML]{AE2892}{\textcolor{white}{\textbf{41}}}\\
\addlinespace[0.3em]
\multicolumn{7}{l}{\textbf{CNG auto-rickshaw}}\\
\hspace{1em}Never & \cellcolor[HTML]{0D0887}{\textcolor{white}{\textbf{176}}} & \cellcolor[HTML]{F79044}{\textcolor{white}{\textbf{14}}} & \cellcolor[HTML]{FBA238}{\textcolor{white}{\textbf{3}}} & \cellcolor[HTML]{FCA537}{\textcolor{white}{\textbf{1}}} & \cellcolor[HTML]{FCA636}{\textcolor{white}{\textbf{0}}} & \cellcolor[HTML]{FCA636}{\textcolor{white}{\textbf{0}}}\\
\hspace{1em}Rarely & \cellcolor[HTML]{0D0887}{\textcolor{white}{\textbf{213}}} & \cellcolor[HTML]{BE3885}{\textcolor{white}{\textbf{95}}} & \cellcolor[HTML]{F89441}{\textcolor{white}{\textbf{14}}} & \cellcolor[HTML]{FBA238}{\textcolor{white}{\textbf{4}}} & \cellcolor[HTML]{FCA636}{\textcolor{white}{\textbf{1}}} & \cellcolor[HTML]{FCA438}{\textcolor{white}{\textbf{3}}}\\
\hspace{1em}Once a week & \cellcolor[HTML]{280592}{\textcolor{white}{\textbf{36}}} & \cellcolor[HTML]{5901A5}{\textcolor{white}{\textbf{31}}} & \cellcolor[HTML]{0D0887}{\textcolor{white}{\textbf{38}}} & \cellcolor[HTML]{E97158}{\textcolor{white}{\textbf{9}}} & \cellcolor[HTML]{FCA636}{\textcolor{white}{\textbf{2}}} & \cellcolor[HTML]{FA9E3B}{\textcolor{white}{\textbf{3}}}\\
\hspace{1em}2-3 times per week & \cellcolor[HTML]{0D0887}{\textcolor{white}{\textbf{29}}} & \cellcolor[HTML]{9D189D}{\textcolor{white}{\textbf{18}}} & \cellcolor[HTML]{B12A90}{\textcolor{white}{\textbf{16}}} & \cellcolor[HTML]{C23C81}{\textcolor{white}{\textbf{14}}} & \cellcolor[HTML]{E97257}{\textcolor{white}{\textbf{8}}} & \cellcolor[HTML]{FCA636}{\textcolor{white}{\textbf{3}}}\\
\hspace{1em}4-5 times per week & \cellcolor[HTML]{310597}{\textcolor{white}{\textbf{13}}} & \cellcolor[HTML]{CA457A}{\textcolor{white}{\textbf{6}}} & \cellcolor[HTML]{D8576B}{\textcolor{white}{\textbf{5}}} & \cellcolor[HTML]{930FA3}{\textcolor{white}{\textbf{9}}} & \cellcolor[HTML]{0D0887}{\textcolor{white}{\textbf{14}}} & \cellcolor[HTML]{FCA636}{\textcolor{white}{\textbf{1}}}\\
\hspace{1em}Almost daily & \cellcolor[HTML]{0D0887}{\textcolor{white}{\textbf{8}}} & \cellcolor[HTML]{42039E}{\textcolor{white}{\textbf{7}}} & \cellcolor[HTML]{E16462}{\textcolor{white}{\textbf{2}}} & \cellcolor[HTML]{FCA636}{\textcolor{white}{\textbf{0}}} & \cellcolor[HTML]{FCA636}{\textcolor{white}{\textbf{0}}} & \cellcolor[HTML]{B12A90}{\textcolor{white}{\textbf{4}}}\\
\addlinespace[0.3em]
\multicolumn{7}{l}{\textbf{bus}}\\
\hspace{1em}Never & \cellcolor[HTML]{0D0887}{\textcolor{white}{\textbf{116}}} & \cellcolor[HTML]{F79044}{\textcolor{white}{\textbf{9}}} & \cellcolor[HTML]{FA9E3B}{\textcolor{white}{\textbf{3}}} & \cellcolor[HTML]{FCA636}{\textcolor{white}{\textbf{0}}} & \cellcolor[HTML]{FCA636}{\textcolor{white}{\textbf{0}}} & \cellcolor[HTML]{FCA636}{\textcolor{white}{\textbf{0}}}\\
\hspace{1em}Rarely & \cellcolor[HTML]{0D0887}{\textcolor{white}{\textbf{155}}} & \cellcolor[HTML]{D9586A}{\textcolor{white}{\textbf{46}}} & \cellcolor[HTML]{F89540}{\textcolor{white}{\textbf{9}}} & \cellcolor[HTML]{FCA636}{\textcolor{white}{\textbf{0}}} & \cellcolor[HTML]{FCA636}{\textcolor{white}{\textbf{0}}} & \cellcolor[HTML]{FCA438}{\textcolor{white}{\textbf{1}}}\\
\hspace{1em}Once a week & \cellcolor[HTML]{0D0887}{\textcolor{white}{\textbf{73}}} & \cellcolor[HTML]{BE3885}{\textcolor{white}{\textbf{32}}} & \cellcolor[HTML]{D8576B}{\textcolor{white}{\textbf{22}}} & \cellcolor[HTML]{F9973F}{\textcolor{white}{\textbf{4}}} & \cellcolor[HTML]{FCA636}{\textcolor{white}{\textbf{0}}} & \cellcolor[HTML]{FCA636}{\textcolor{white}{\textbf{0}}}\\
\hspace{1em}2-3 times per week & \cellcolor[HTML]{0D0887}{\textcolor{white}{\textbf{43}}} & \cellcolor[HTML]{BE3885}{\textcolor{white}{\textbf{19}}} & \cellcolor[HTML]{E06363}{\textcolor{white}{\textbf{11}}} & \cellcolor[HTML]{ED7A53}{\textcolor{white}{\textbf{7}}} & \cellcolor[HTML]{F3854B}{\textcolor{white}{\textbf{5}}} & \cellcolor[HTML]{FCA636}{\textcolor{white}{\textbf{0}}}\\
\hspace{1em}4-5 times per week & \cellcolor[HTML]{0D0887}{\textcolor{white}{\textbf{60}}} & \cellcolor[HTML]{F68E45}{\textcolor{white}{\textbf{6}}} & \cellcolor[HTML]{F79442}{\textcolor{white}{\textbf{5}}} & \cellcolor[HTML]{F9983E}{\textcolor{white}{\textbf{4}}} & \cellcolor[HTML]{E97357}{\textcolor{white}{\textbf{12}}} & \cellcolor[HTML]{FCA636}{\textcolor{white}{\textbf{1}}}\\
\hspace{1em}Almost daily & \cellcolor[HTML]{0D0887}{\textcolor{white}{\textbf{103}}} & \cellcolor[HTML]{E97357}{\textcolor{white}{\textbf{21}}} & \cellcolor[HTML]{F79044}{\textcolor{white}{\textbf{10}}} & \cellcolor[HTML]{F68C45}{\textcolor{white}{\textbf{11}}} & \cellcolor[HTML]{FCA636}{\textcolor{white}{\textbf{2}}} & \cellcolor[HTML]{F79044}{\textcolor{white}{\textbf{10}}}\\
\addlinespace[0.3em]
\multicolumn{7}{l}{\textbf{motorcycle}}\\
\hspace{1em}Never & \cellcolor[HTML]{0D0887}{\textcolor{white}{\textbf{467}}} & \cellcolor[HTML]{F99A3E}{\textcolor{white}{\textbf{22}}} & \cellcolor[HTML]{FB9F3A}{\textcolor{white}{\textbf{12}}} & \cellcolor[HTML]{FCA537}{\textcolor{white}{\textbf{3}}} & \cellcolor[HTML]{FCA636}{\textcolor{white}{\textbf{1}}} & \cellcolor[HTML]{FBA238}{\textcolor{white}{\textbf{8}}}\\
\hspace{1em}Rarely & \cellcolor[HTML]{0D0887}{\textcolor{white}{\textbf{44}}} & \cellcolor[HTML]{46039F}{\textcolor{white}{\textbf{38}}} & \cellcolor[HTML]{DA5A6A}{\textcolor{white}{\textbf{13}}} & \cellcolor[HTML]{E56A5D}{\textcolor{white}{\textbf{10}}} & \cellcolor[HTML]{FCA636}{\textcolor{white}{\textbf{0}}} & \cellcolor[HTML]{F68C45}{\textcolor{white}{\textbf{4}}}\\
\hspace{1em}Once a week & \cellcolor[HTML]{DF6263}{\textcolor{white}{\textbf{11}}} & \cellcolor[HTML]{DF6263}{\textcolor{white}{\textbf{11}}} & \cellcolor[HTML]{0D0887}{\textcolor{white}{\textbf{34}}} & \cellcolor[HTML]{FCA636}{\textcolor{white}{\textbf{3}}} & \cellcolor[HTML]{FCA636}{\textcolor{white}{\textbf{3}}} & \cellcolor[HTML]{FCA636}{\textcolor{white}{\textbf{3}}}\\
\hspace{1em}2-3 times per week & \cellcolor[HTML]{4B03A1}{\textcolor{white}{\textbf{13}}} & \cellcolor[HTML]{D8576B}{\textcolor{white}{\textbf{6}}} & \cellcolor[HTML]{D8576B}{\textcolor{white}{\textbf{6}}} & \cellcolor[HTML]{0D0887}{\textcolor{white}{\textbf{15}}} & \cellcolor[HTML]{EF7C51}{\textcolor{white}{\textbf{4}}} & \cellcolor[HTML]{FCA636}{\textcolor{white}{\textbf{2}}}\\
\hspace{1em}4-5 times per week & \cellcolor[HTML]{C13B82}{\textcolor{white}{\textbf{6}}} & \cellcolor[HTML]{DB5C68}{\textcolor{white}{\textbf{4}}} & \cellcolor[HTML]{FCA636}{\textcolor{white}{\textbf{0}}} & \cellcolor[HTML]{DB5C68}{\textcolor{white}{\textbf{4}}} & \cellcolor[HTML]{0D0887}{\textcolor{white}{\textbf{14}}} & \cellcolor[HTML]{E66C5C}{\textcolor{white}{\textbf{3}}}\\
\hspace{1em}Almost daily & \cellcolor[HTML]{FCA636}{\textcolor{white}{\textbf{1}}} & \cellcolor[HTML]{F68C45}{\textcolor{white}{\textbf{3}}} & \cellcolor[HTML]{F9993E}{\textcolor{white}{\textbf{2}}} & \cellcolor[HTML]{F0804E}{\textcolor{white}{\textbf{4}}} & \cellcolor[HTML]{F68C45}{\textcolor{white}{\textbf{3}}} & \cellcolor[HTML]{0D0887}{\textcolor{white}{\textbf{23}}}\\
\addlinespace[0.3em]
\multicolumn{7}{l}{\textbf{walk}}\\
\hspace{1em}Never & \cellcolor[HTML]{0D0887}{\textcolor{white}{\textbf{17}}} & \cellcolor[HTML]{C43E7F}{\textcolor{white}{\textbf{7}}} & \cellcolor[HTML]{EB7655}{\textcolor{white}{\textbf{3}}} & \cellcolor[HTML]{E3685F}{\textcolor{white}{\textbf{4}}} & \cellcolor[HTML]{FCA636}{\textcolor{white}{\textbf{0}}} & \cellcolor[HTML]{F3854B}{\textcolor{white}{\textbf{2}}}\\
\hspace{1em}Rarely & \cellcolor[HTML]{B7318A}{\textcolor{white}{\textbf{26}}} & \cellcolor[HTML]{0D0887}{\textcolor{white}{\textbf{53}}} & \cellcolor[HTML]{E66C5C}{\textcolor{white}{\textbf{13}}} & \cellcolor[HTML]{F79044}{\textcolor{white}{\textbf{6}}} & \cellcolor[HTML]{FCA636}{\textcolor{white}{\textbf{2}}} & \cellcolor[HTML]{FA9B3D}{\textcolor{white}{\textbf{4}}}\\
\hspace{1em}Once a week & \cellcolor[HTML]{E97257}{\textcolor{white}{\textbf{12}}} & \cellcolor[HTML]{D5536F}{\textcolor{white}{\textbf{19}}} & \cellcolor[HTML]{0D0887}{\textcolor{white}{\textbf{54}}} & \cellcolor[HTML]{F1814D}{\textcolor{white}{\textbf{9}}} & \cellcolor[HTML]{FA9B3D}{\textcolor{white}{\textbf{4}}} & \cellcolor[HTML]{FCA636}{\textcolor{white}{\textbf{2}}}\\
\hspace{1em}2-3 times per week & \cellcolor[HTML]{DD5E66}{\textcolor{white}{\textbf{10}}} & \cellcolor[HTML]{BB3488}{\textcolor{white}{\textbf{14}}} & \cellcolor[HTML]{CD4A76}{\textcolor{white}{\textbf{12}}} & \cellcolor[HTML]{0D0887}{\textcolor{white}{\textbf{26}}} & \cellcolor[HTML]{C5407E}{\textcolor{white}{\textbf{13}}} & \cellcolor[HTML]{FCA636}{\textcolor{white}{\textbf{4}}}\\
\hspace{1em}4-5 times per week & \cellcolor[HTML]{D8576B}{\textcolor{white}{\textbf{7}}} & \cellcolor[HTML]{FCA636}{\textcolor{white}{\textbf{3}}} & \cellcolor[HTML]{D8576B}{\textcolor{white}{\textbf{7}}} & \cellcolor[HTML]{930FA3}{\textcolor{white}{\textbf{11}}} & \cellcolor[HTML]{0D0887}{\textcolor{white}{\textbf{16}}} & \cellcolor[HTML]{CA457A}{\textcolor{white}{\textbf{8}}}\\
\hspace{1em}Almost daily & \cellcolor[HTML]{F3874A}{\textcolor{white}{\textbf{46}}} & \cellcolor[HTML]{DE5F65}{\textcolor{white}{\textbf{73}}} & \cellcolor[HTML]{F79143}{\textcolor{white}{\textbf{40}}} & \cellcolor[HTML]{F1824C}{\textcolor{white}{\textbf{49}}} & \cellcolor[HTML]{FCA636}{\textcolor{white}{\textbf{27}}} & \cellcolor[HTML]{0D0887}{\textcolor{white}{\textbf{197}}}\\
\addlinespace[0.3em]
\multicolumn{7}{l}{\textbf{bicycle}}\\
\hspace{1em}Never & \cellcolor[HTML]{0D0887}{\textcolor{white}{\textbf{504}}} & \cellcolor[HTML]{FA9B3D}{\textcolor{white}{\textbf{22}}} & \cellcolor[HTML]{FCA238}{\textcolor{white}{\textbf{7}}} & \cellcolor[HTML]{FCA537}{\textcolor{white}{\textbf{4}}} & \cellcolor[HTML]{FCA636}{\textcolor{white}{\textbf{2}}} & \cellcolor[HTML]{FCA537}{\textcolor{white}{\textbf{4}}}\\
\hspace{1em}Rarely & \cellcolor[HTML]{0D0887}{\textcolor{white}{\textbf{59}}} & \cellcolor[HTML]{7501A8}{\textcolor{white}{\textbf{43}}} & \cellcolor[HTML]{D5546E}{\textcolor{white}{\textbf{20}}} & \cellcolor[HTML]{FA9C3C}{\textcolor{white}{\textbf{4}}} & \cellcolor[HTML]{FCA636}{\textcolor{white}{\textbf{2}}} & \cellcolor[HTML]{FA9C3C}{\textcolor{white}{\textbf{4}}}\\
\hspace{1em}Once a week & \cellcolor[HTML]{8808A6}{\textcolor{white}{\textbf{14}}} & \cellcolor[HTML]{9714A1}{\textcolor{white}{\textbf{13}}} & \cellcolor[HTML]{0D0887}{\textcolor{white}{\textbf{21}}} & \cellcolor[HTML]{F58B47}{\textcolor{white}{\textbf{3}}} & \cellcolor[HTML]{F9983E}{\textcolor{white}{\textbf{2}}} & \cellcolor[HTML]{FCA636}{\textcolor{white}{\textbf{1}}}\\
\hspace{1em}2-3 times per week & \cellcolor[HTML]{C13B82}{\textcolor{white}{\textbf{3}}} & \cellcolor[HTML]{9E199D}{\textcolor{white}{\textbf{4}}} & \cellcolor[HTML]{7601A8}{\textcolor{white}{\textbf{5}}} & \cellcolor[HTML]{0D0887}{\textcolor{white}{\textbf{7}}} & \cellcolor[HTML]{DB5C68}{\textcolor{white}{\textbf{2}}} & \cellcolor[HTML]{FCA636}{\textcolor{white}{\textbf{0}}}\\
\hspace{1em}4-5 times per week & \cellcolor[HTML]{F1844C}{\textcolor{white}{\textbf{2}}} & \cellcolor[HTML]{F1844C}{\textcolor{white}{\textbf{2}}} & \cellcolor[HTML]{CB4679}{\textcolor{white}{\textbf{4}}} & \cellcolor[HTML]{FCA636}{\textcolor{white}{\textbf{1}}} & \cellcolor[HTML]{0D0887}{\textcolor{white}{\textbf{9}}} & \cellcolor[HTML]{E16462}{\textcolor{white}{\textbf{3}}}\\
\hspace{1em}Almost daily & \cellcolor[HTML]{C6417D}{\textcolor{white}{\textbf{7}}} & \cellcolor[HTML]{FCA636}{\textcolor{white}{\textbf{1}}} & \cellcolor[HTML]{FCA636}{\textcolor{white}{\textbf{1}}} & \cellcolor[HTML]{FCA636}{\textcolor{white}{\textbf{1}}} & \cellcolor[HTML]{F1814D}{\textcolor{white}{\textbf{3}}} & \cellcolor[HTML]{0D0887}{\textcolor{white}{\textbf{16}}}\\
\bottomrule
\multicolumn{7}{l}{\rule{0pt}{1em}\textit{Note: }}\\
\multicolumn{7}{l}{\rule{0pt}{1em}Darker cell colors indicate higher cell values in a row.}\\
\end{tabular}}
\end{table}

The frequency of trip-making by other modes changed more noticeably: the
frequency of travel by ride-hailing services, rickshaw, CNG
auto-rickshaw, and bus collapsed, with vastly more respondents reporting
never using these modes during the pandemic than before. The frequency
of walking trips also decreased (fewer respondents report walking almost
daily), but the reductions in mobility were not so heavily concentrated
at the bottom of the scale.

Table \ref{tab:cross-tabulation} is a cross-tabulation of the number of
cases in each trip-making frequency class before and during the
pandemic. If no changes had occurred, all values would be concentrated
on the main diagonal of the matrices. Values in the lower triangular
matrix represent a \emph{loss} of mobility (lower travel frequency),
whereas values in the upper triangular matrix are \emph{gains} (higher
travel frequency). The further away a value is from the main diagonal,
the greater the loss or gain.

Despite across-the-board losses of mobility, there appears to have been
some adaptation that varied by mode of transportation. To illustrate,
103 respondents, or 65.61\% of those who traveled by bus almost daily
before, reported never using it during the pandemic. In contrast, only
12 respondents, or 1.5\% of those who never used buses before started
doing so during the pandemic. By way of comparison, 24.14\% of
respondents who cycled almost daily before the pandemic stopped doing so
- but 4.88\% who never cycled before started doing so during the
pandemic.

To more clearly understand the transitions towards different trip-making
frequencies, including possible adaptations, we convert the
cross-tabulations to probability transition matrices, which we then
visualize using circular plots.

Figures \ref{fig:circular-plot-1} to \ref{fig:circular-plot-4} present
these plots. Each of the trip-making frequency sectors on the left
hemisphere of the circle represents 100\% of responses \emph{before} the
pandemic. The links' size is proportional to the probability \(p_{ij}\)
of transitioning from frequency class \(i\) before to the right
hemisphere are proportional to the transition probabilities to each
frequency \emph{during} the pandemic. There are three transparency
levels for the links: solid colors are for \(p_{ij}>2/3\), intermediate
transparency is for \(1/3 < p_{ij} \le 2/3\), and the more transparent
links are for \(p_{ij}\le 1/3\).

From Figure \ref{fig:circular-plot-1}, we see that the probability of
traveling less by car for those who initially used this mode frequently
is high, but their probability of not using this mode at all during the
pandemic is quite small. In other words, there was a decline in use, but
not complete discontinuation of this mode. The probability of traveling
more frequently by car for those who originally never or rarely used
this mode remained is low. In contrast, we see that the probabilities of
never ride-hailing during the pandemic are high irrespective of the
initial level of use of this mode of transportation, and the probability
of using this mode more are fairly small.

\begin{figure}
\centering
\includegraphics{Frequency-of-Travel-by-Mode-COVID-19-Bangladesh_files/figure-latex/circular-plots-transition-probabilities-1-1.pdf}
\caption{\label{fig:circular-plot-1}Transition probabilities in trip
frequency from before to during COVID-19: car and ride-hailing}
\end{figure}

The probabilities of change in trip frequency by rickshaw and CNG
auto-rickshaw are similar (see Figure \ref{fig:circular-plot-2}),
although the probabilities of being less mobile by CNG auto-rickshaw are
greater: between 1/3 and 2/3 of respondents who used this mode almost
daily, stopped using it during the pandemic. Very rarely there were
increases in mobility by these modes.

\begin{figure}
\centering
\includegraphics{Frequency-of-Travel-by-Mode-COVID-19-Bangladesh_files/figure-latex/circular-plots-transition-probabilities-2-1.pdf}
\caption{\label{fig:circular-plot-2}Transition probabilities in trip
frequency from before to during COVID-19: rickshaw and cng
auto-rickshaw}
\end{figure}

After ride-hailing, the use of bus had the largest probabilities of
discontinuation (Figure \ref{fig:circular-plot-3}). We see that even
respondents who used this mode almost daily before the pandemic had
close to 66\% chances of never using it during the contingency.
Similarly large losses of mobility by bus were observed for travelers
who used this mode less frequently before the pandemic. These losses
were not offset to any appreciable degree by the probability of some
users turning to this mode during the pandemic.

\begin{figure}
\centering
\includegraphics{Frequency-of-Travel-by-Mode-COVID-19-Bangladesh_files/figure-latex/circular-plots-transition-probabilities-3-1.pdf}
\caption{\label{fig:circular-plot-3}Transition probabilities in trip
frequency from before to during COVID-19: motorcycle and bus}
\end{figure}

Trip-making by motorcycle (Figure \ref{fig:circular-plot-3}) also
declined for all but the most frequent users pre-COVID-19, and the
probability of adopting this mode during COVID-19 was almost null.
Contrast this to the case of walking (Figure \ref{fig:circular-plot-4}),
where a sizable number of respondents started walking during the
pandemic, even if only rarely. Close to 50\% of respondents who report
walking almost daily during the pandemic walked less frequently before
the contingency. Bicycle (Figure \ref{fig:circular-plot-4}), like
motorcycle, saw relatively fewer respondents adopting it during the
pandemic, and many travelers who did use the mode rarely, once a week,
or even 2-3 times per week stopped cycling during the pandemic.

\begin{figure}
\centering
\includegraphics{Frequency-of-Travel-by-Mode-COVID-19-Bangladesh_files/figure-latex/circular-plots-transition-probabilities-4-1.pdf}
\caption{\label{fig:circular-plot-4}Transition probabilities in trip
frequency from before to during COVID-19: bicycle and walk}
\end{figure}

The findings reported here suggest important changes in mobility in a
developing country during COVID-19, which (given the characteristics of
the convenience sample) may be more representative of younger, urban
residents in Bangladesh. In general there was a loss of mobility
across-the-board, but modes that require interaction with strangers
(ride-hailing, bus, rickshaw, and CNG auto-rickshaw) were more affected.
Travel by car, motorcycle, and bicycle were somewhat less affected, and
there is evidence of some adoption of walking during the pandemic.

\hypertarget{references}{%
\section*{References}\label{references}}
\addcontentsline{toc}{section}{References}

\hypertarget{refs}{}
\leavevmode\hypertarget{ref-Astroza2020mobility}{}%
Astroza, S., Tirachini, A., Hurtubia, R., Carrasco, J.A., Guevara, A.,
Munizaga, M., Figueroa, M., Torres, V., 2020. Mobility changes,
teleworking, and remote communication during the covid-19 pandemic in
chile. Transport Findings.
doi:\href{https://doi.org/10.32866/001c.13489}{10.32866/001c.13489}

\leavevmode\hypertarget{ref-Bangladesh2015}{}%
Bangladesh Bureau of Statistics, 2015. Population monograph of
bangladesh. Age-sex composition of bangladesh population.

\leavevmode\hypertarget{ref-Brunsdon2020opening}{}%
Brunsdon, C., Comber, A., 2020. Opening practice: Supporting
reproducibility and critical spatial data science. Journal of
Geographical Systems 1--20.

\leavevmode\hypertarget{ref-DeWeese2020tale}{}%
DeWeese, J., Hawa, L., Demyk, H., Davey, Z., Belikow, A., El-geneidy,
A., 2020. A tale of 40 cities: A preliminary analysis of equity impacts
of covid-19 service adjustments across north america. Tansport Findings.
doi:\href{https://doi.org/10.32866/001c.13395}{10.32866/001c.13395}

\leavevmode\hypertarget{ref-Fricker2002advantages}{}%
Fricker, R.D., Schonlau, M., 2002. Advantages and disadvantages of
internet research surveys: Evidence from the literature. Field methods
14, 347--367.

\leavevmode\hypertarget{ref-Huynh2020culture}{}%
Huynh, T.L.D., 2020. Does culture matter social distancing under the
covid-19 pandemic? Safety Science 130, 7.
doi:\href{https://doi.org/10.1016/j.ssci.2020.104872}{10.1016/j.ssci.2020.104872}

\leavevmode\hypertarget{ref-Jager2017convenience}{}%
Jager, J., Putnick, D.L., Bornstein, M.H., 2017. II. MORE than just
convenient: THE scientific merits of homogeneous convenience samples.
Monographs of the Society for Research in Child Development 82, 13--30.
doi:\href{https://doi.org/10.1111/mono.12296}{10.1111/mono.12296}

\leavevmode\hypertarget{ref-Jamal2020perceptions}{}%
Jamal, S., Mohiuddin, H., Paez, A., 2020. How do the perceptions of
neighborhood conditions impact active transportation? A study in
rajshahi, bangladesh. Transportation Research Part D: Transport and
Environment 87, 102525.

\leavevmode\hypertarget{ref-Lock2020cycling}{}%
Lock, O., 2020. Cycling behaviour changes as a result of covid-19: A
survey of users in sydney, australia. Transport Findings.
doi:\href{https://doi.org/10.32866/001c.13405}{10.32866/001c.13405}

\leavevmode\hypertarget{ref-Molloy2020tracing}{}%
Molloy, J., Tchervenkov, C., Hintermann, B., Axhausen, K.W., 2020.
Tracing the sars-cov-2 impact: The first month in switzerland. Transport
Findings.
doi:\href{https://doi.org/10.32866/001c.12903}{10.32866/001c.12903}

\leavevmode\hypertarget{ref-Paez2020using}{}%
Paez, A., 2020. Using google community mobility reports to investigate
the incidence of covid-19 in the united states. Transport Findings.
doi:\href{https://doi.org/10.32866/001c.12976}{10.32866/001c.12976}

\leavevmode\hypertarget{ref-Saha2020lockdown}{}%
Saha, J., Barman, B., Chouhan, P., 2020. Lockdown for covid-19 and its
impact on community mobility in india: An analysis of the covid-19
community mobility reports, 2020. Children and Youth Services Review
116, 14.
doi:\href{https://doi.org/10.1016/j.childyouth.2020.105160}{10.1016/j.childyouth.2020.105160}


\end{document}


